package DistributedFileSystem;


/**
* DistributedFileSystem/DFSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFileSystem.idl
* Wednesday, December 13, 2017 7:04:15 PM EST
*/

abstract public class DFSHelper
{
  private static String  _id = "IDL:DistributedFileSystem/DFS:1.0";

  public static void insert (org.omg.CORBA.Any a, DistributedFileSystem.DFS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DistributedFileSystem.DFS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DistributedFileSystem.DFSHelper.id (), "DFS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DistributedFileSystem.DFS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DFSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DistributedFileSystem.DFS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DistributedFileSystem.DFS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DistributedFileSystem.DFS)
      return (DistributedFileSystem.DFS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DistributedFileSystem._DFSStub stub = new DistributedFileSystem._DFSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DistributedFileSystem.DFS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DistributedFileSystem.DFS)
      return (DistributedFileSystem.DFS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DistributedFileSystem._DFSStub stub = new DistributedFileSystem._DFSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
