package DistributedFileSystem;

/**
* DistributedFileSystem/DFSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFileSystem.idl
* Wednesday, December 13, 2017 7:04:15 PM EST
*/

public final class DFSHolder implements org.omg.CORBA.portable.Streamable
{
  public DistributedFileSystem.DFS value = null;

  public DFSHolder ()
  {
  }

  public DFSHolder (DistributedFileSystem.DFS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DistributedFileSystem.DFSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DistributedFileSystem.DFSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DistributedFileSystem.DFSHelper.type ();
  }

}
