package DistributedFileSystem;


/**
* DistributedFileSystem/DFSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFileSystem.idl
* Wednesday, December 13, 2017 7:04:15 PM EST
*/

public interface DFSOperations 
{
  String openFile (String fileName);
  String readFile (String fileName, String recordNum);
  String closeFile (String fileName);
  String getFileList ();
  String getOpenFiles ();
  String getFile (String fileName);
  String lockFile (String fileName);
  String unlockFile (String fileName);
} // interface DFSOperations
