package DistributedFileSystem;


/**
* DistributedFileSystem/DFSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFileSystem.idl
* Wednesday, December 13, 2017 7:04:15 PM EST
*/

public abstract class DFSPOA extends org.omg.PortableServer.Servant
 implements DistributedFileSystem.DFSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("openFile", new java.lang.Integer (0));
    _methods.put ("readFile", new java.lang.Integer (1));
    _methods.put ("closeFile", new java.lang.Integer (2));
    _methods.put ("getFileList", new java.lang.Integer (3));
    _methods.put ("getOpenFiles", new java.lang.Integer (4));
    _methods.put ("getFile", new java.lang.Integer (5));
    _methods.put ("lockFile", new java.lang.Integer (6));
    _methods.put ("unlockFile", new java.lang.Integer (7));

  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DistributedFileSystem/DFS/openFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.openFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DistributedFileSystem/DFS/readFile
       {
         String fileName = in.read_string ();
         String recordNum = in.read_string ();
         String $result = null;
         System.out.println("Beginning to read file: " + fileName);
         $result = this.readFile (fileName, recordNum);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DistributedFileSystem/DFS/closeFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.closeFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DistributedFileSystem/DFS/getFileList
       {
         String $result = null;
         $result = this.getFileList ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DistributedFileSystem/DFS/getOpenFiles
       {
         String $result = null;
         $result = this.getOpenFiles ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DistributedFileSystem/DFS/getFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.getFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DistributedFileSystem/DFS/lockFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.lockFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DistributedFileSystem/DFS/unlockFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.unlockFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DistributedFileSystem/DFS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DFS _this() 
  {
    return DFSHelper.narrow(
    super._this_object());
  }

  public DFS _this(org.omg.CORBA.ORB orb) 
  {
    return DFSHelper.narrow(
    super._this_object(orb));
  }


} // class DFSPOA
